package com.bastex.codelearninghub.jakartaee.jms.taskmanager.client;

import com.bastex.codelearninghub.jakartaee.jms.taskmanager.client.messagelisteners.ServerNotificationMessageListener;
import com.bastex.codelearninghub.jakartaee.jms.taskmanager.client.messagelisteners.TaskReplyMessageListener;
import com.bastex.codelearninghub.jakartaee.jms.taskmanager.client.utils.TaskFromCLICreator;
import com.bastex.codelearninghub.jakartaee.jms.taskmanager.common.TaskManagerCommonProperties;
import com.bastex.codelearninghub.jakartaee.jms.taskmanager.common.handlers.MessagesFromCLIHandler;
import com.bastex.codelearninghub.jakartaee.jms.taskmanager.common.handlers.MessagesFromCLIHandlerFactory;
import com.bastex.codelearninghub.jakartaee.jms.taskmanager.common.model.tasks.requests.TaskRequest;
import lombok.extern.slf4j.Slf4j;
import org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory;

import javax.jms.JMSConsumer;
import javax.jms.JMSContext;
import javax.jms.Queue;
import javax.jms.Topic;
import javax.naming.InitialContext;
import java.util.Scanner;

@Slf4j
public class TaskManagerClientApp {
    public static void main(final String[] args) throws Exception {
        final InitialContext initialContext = new InitialContext();
        final Queue taskRequestQueue = (Queue) initialContext.lookup("queue/taskRequestQueue");
        final Queue taskReplyQueue = (Queue) initialContext.lookup("queue/taskReplyQueue");
        final Topic notificationTopic = (Topic) initialContext.lookup("topic/notificationTopic");

        try (final ActiveMQConnectionFactory connectionFactory = new ActiveMQConnectionFactory();
             final JMSContext jmsContext = connectionFactory.createContext()) {
            jmsContext.setClientID("task-manager-client-1");
            initializeMessageConsumers(jmsContext, taskReplyQueue, notificationTopic);

            log.info("Task Manager Client started");
            final MessagesFromCLIHandler<TaskRequest> messagesFromCLIHandler = prepareMessagesHandler(jmsContext, taskRequestQueue, taskReplyQueue);
            messagesFromCLIHandler.handleMessagesFromCLI();

            Thread.currentThread().join();
        }
    }

    private static MessagesFromCLIHandler<TaskRequest> prepareMessagesHandler(final JMSContext jmsContext, final Queue taskRequestQueue, final Queue taskReplyQueue) {
        final TaskFromCLICreator taskFromCLICreator = new TaskFromCLICreator(new Scanner(System.in));
        return MessagesFromCLIHandlerFactory.createHandlerWithReply(jmsContext,
                taskRequestQueue,
                taskReplyQueue,
                taskFromCLICreator::createTaskFromUserInput);
    }

    private static void initializeMessageConsumers(final JMSContext jmsContext, final Queue taskReplyQueue, final Topic notificationTopic) {
        // we consume task replies only for tasks generated by this specific client
        final String messageFilterQuery = TaskManagerCommonProperties.TASK_MANAGER_CLIENT_ID + "=" + jmsContext.getClientID();
        final JMSConsumer taskReplyConsumer = jmsContext.createConsumer(taskReplyQueue, messageFilterQuery);
        taskReplyConsumer.setMessageListener(new TaskReplyMessageListener());

        final JMSConsumer notificationConsumer = jmsContext.createConsumer(notificationTopic);
        notificationConsumer.setMessageListener(new ServerNotificationMessageListener());
    }
}
